### PR TITLE
Fixes some premature changes from PR #55.

### LINKED ISSUE #56: semantic conditions for ground graphs damaged
PR #52 has changed the semantic conditions for ground graphs by changing the scope of the otherwise parts of clauses.  This needs to be undone.  The best way to do this is to undo PR #52, which should not have included substantive changes.

### PR DESCRIPTION
**Pull request by gkellogg**
There were a couple of areas where the changes were significant that are rolled back here.

Fixes #56.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 3, 2024, 5:43 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Frdf-semantics%2Fc6b4a4a1f86f9d915f9c07d5bead4285e1cc86e9%2Fspec%2Findex.html%3FisPreview%3Dtrue)

```
Timed out after waiting 30000ms
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/rdf-semantics%2357.)._
</details>

### CODE REVIEW

**Review by domel — APPROVED** [review]

**Comment by TallTed** [comment]
I'm fairly certain that these are not the changes in #55 that @pfps found problematic.

I'm more certain that I will be suggesting these changes again, whether as my own PR or as change requests on this or another PR. The phrasing of the complex `if x then z if y` statements being applied (restored) by this PR is *much* less clear to the reader than the `if x and y then z` phrasing I suggested via #55. None of my textual edits changed the meaning of the text; they just restructured the presentation of the complex if/then statements.

**Comment by gkellogg** [comment]
I agree that the wording, which was restored in the PR, is problematic. But looking at the HTML diff, these were the only substantive changes i saw. The point was to get back to the content before the PR, as the objection was that both the amount of markup change and the different wording of the semantic conditions shouldn’t have been done at the same time.

**Comment by pfps** [comment]
'If ... then ... if ... otherwise ..." is a traditional way of stating a particular kind of conditional.  It has a different meaning than "If ... and ... then ... otherwise ..."

**Comment by pfps** [comment]
> I agree that the wording, which was restored in the PR, is problematic. But looking at the HTML diff, these were the only substantive changes i saw. The point was to get back to the content before the PR, as the objection was that both the amount of markup change and the different wording of the semantic conditions shouldn’t have been done at the same time.

The right way to get back to the undamaged state is to revert the "editorial" PR, create a truly editorial PR, and apply that.

**Review by pfps — CHANGES_REQUESTED** [review]
Revert #52 first.

**Comment by afs** [comment]
https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/52/e29d0aa...84888af.html shows the non-HTML differences. It is readable. This was discussed at the [WG meeting of 2024-11-21](https://www.w3.org/2024/11/21-rdf-star-minutes.html#2764).

What non-HTML format issues are there other than the two items reverted by this PR (#57)?

**Comment by TallTed** [comment]
"https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/52/e29d0aa...84888af.html shows the" **_404_** "non-HTML differences."

It appears to me that there are many HTML differences within that preview, primarily but not only 100+ added `<em>`...`</em>` wrappers. One large (non-`<em>`) example is [change 231 of the 404](https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/52/e29d0aa...84888af.html#RDFS_axiomatic_triples).

**Comment by afs** [comment]
> example is [change 231 of the 404](https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/52/e29d0aa...84888af.html#RDFS_axiomatic_triples).

Thee layout seems to be an artefact of the diff tool

The current editors working draft shows the PR input appearance:
https://www.w3.org/TR/rdf12-semantics/#RDFS_axiomatic_triples

**Comment by gkellogg** [comment]
> > example is [change 231 of the 404](https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/52/e29d0aa...84888af.html#RDFS_axiomatic_triples).
> 
> Thee layout seems to be an artefact of the diff tool
> 
> The current editors working draft shows the PR input appearance: https://www.w3.org/TR/rdf12-semantics/#RDFS_axiomatic_triples

Yes, a visual examination shows just a couple of changes in white-space. HTML diff is not a perfect tool, particularly when it comes to `pre` blocks.

Unless there's a concern about the legitimacy of some HTML markup, I think it would be better to confine objections to the rendered content. Sometimes, HTML diff is enough, other times you need to bring up windows next to each other to visually compare.

In a perfect world, changes to markup/structure would not introduce any other changes in content, but it ends up happening due to human nature and the perceived block of needing to have a PR merged before those additional changes can be made. With our deliberate delays in merging PRs, this can have the affect of stringing things out over quite a long time.

**Comment by pfps** [comment]
On a quick perusal of PR #52 HTML diff, I see at least 19 areas where the changes are not just better HTML.   When I did a very careful examination, the second one of these made substantive changes to a core definition of the RDF semantics.   I have no confidence that the other non-HTML change areas did not also make substantive changes.

So, the only acceptable way forward for me is to revert PR #52 and start over from a state that is known to be good.

**Comment by afs** [comment]
> to a core definition

Peter - I don't understand what part of the document your comment is referring to.
Please give the document location(s).

**Comment by pfps** [comment]
See https://github.com/w3c/rdf-semantics/pull/52#issuecomment-2492261058

**Comment by gkellogg** [comment]
Closing, as the basis of this PR is being reverted.

**Pull request closed without merging**
