### PR TITLE
Update contributors.

### PR DESCRIPTION
**Pull request by gkellogg**

### CODE REVIEW

**Comment by pchampin** [comment]
@gkellogg after reverting #52 per [our resolution today](https://www.w3.org/2024/12/19-rdf-star-minutes.html#4761), I rebased this PR so that you can work on it seamlessly.

**Comment by gkellogg** [comment]
@pchampin We won't be able to merge this after your changes to the baseline. You can just include the contents of /spec/ns/ in your PR to achieve the same thing.

**Comment by pchampin** [comment]
> @pchampin We won't be able to merge this after your changes to the baseline. You can just include the contents of /spec/ns/ in your PR to achieve the same thing.

looks like you were able to merge it afterall, so I assume this comment is moot, right?
In fact, I did [rebase](https://github.com/w3c/rdf-semantics/pull/63#issuecomment-2555522253) this PR precisely to ensure that it could still be merged...

**Comment by gkellogg** [comment]
> looks like you were able to merge it afterall, so I assume this comment is moot, right?
> In fact, I did [rebase](https://github.com/w3c/rdf-semantics/pull/63#issuecomment-2555522253) this PR precisely to ensure that it could still be merged...

Yes, our comments passed each other; all merged now.

**Pull request merged**
