### PR TITLE
Contributors

### PR DESCRIPTION
**Pull request by gkellogg**
Add diagrams.
Add editors, contributors and changes.

@pchampin: please add @pfps, @doerthe, and @timothee-haudebourg as contributors to this repo.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 5, 2023, 9:54 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Frdf-semantics%2F7832df0a61764e79ef55a0767b33e05cc95895e8%2Fspec%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/nYV6vZ/spec/index.html?isPreview=true%3FisPreview%3Dtrue&publishDate=2023-02-05
ReSpec version: 32.7.0
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 28231ms.
    at ExecutionContext._ExecutionContext_evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:252:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/rdf-semantics%234.)._
</details>

### CODE REVIEW

**Comment by gkellogg** [comment]
Until PR Preview picks back up, see it rendered via GitHack: https://raw.githack.com/w3c/rdf-semantics/contributors/spec/index.html.

**Review by timothee-haudebourg — APPROVED** [review]
My name is an capital letters in `spec/common/participants.html` but I've updated my record on W3C so next time the file is generated it should be correct. Apparently it's done from time to time anyway.

**Review by timothee-haudebourg — APPROVED** [review]

**Review by pfps — APPROVED** [review]
I'm not sure why I'm being asked to approve.  There is lots here that doesn't appear to have anything to do with contributors, and lots that I don't understand but I don't see any reason not to merge this in.

**Comment by gkellogg** [comment]
> I'm not sure why I'm being asked to approve. There is lots here that doesn't appear to have anything to do with contributors, and lots that I don't understand but I don't see any reason not to merge this in.

I added you, @doerthe and @timothee-haudebourg as editors, and wanted to give you a chance to comment. Generally, editors should probably be tagged on all PRs to documents they're associated with.

**Pull request merged**
